// <auto-generated />
using System;
using Backend_PruebaTecnica_Lafise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_PruebaTecnica_Lafise.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929001735_EliminarSaldoCuentaBancaria")]
    partial class EliminarSaldoCuentaBancaria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Backend_PruebaTecnica_Lafise.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ingreso")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("sexo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Backend_PruebaTecnica_Lafise.Models.CuentaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("CuentasBancarias");
                });

            modelBuilder.Entity("Backend_PruebaTecnica_Lafise.Models.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CuentaBancariaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAprobado")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Monto")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Saldo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CuentaBancariaId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("Backend_PruebaTecnica_Lafise.Models.CuentaBancaria", b =>
                {
                    b.HasOne("Backend_PruebaTecnica_Lafise.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Backend_PruebaTecnica_Lafise.Models.Transaccion", b =>
                {
                    b.HasOne("Backend_PruebaTecnica_Lafise.Models.CuentaBancaria", "CuentaBancaria")
                        .WithMany()
                        .HasForeignKey("CuentaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaBancaria");
                });
#pragma warning restore 612, 618
        }
    }
}
